In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sales.csv")
df

   Name   Age  Monthly_Salary Department
0   ram  26.0           10000         IT
1  ravi  37.0            3000         HR
2    ak  28.0           40000         IT
3    vj  19.0           50000         HR
4    av   NaN             555         IT
5    rj   3.0             777         HR

In [3]:
# First 5 rows
df.head()

   Name   Age  Monthly_Salary Department
0   ram  26.0           10000         IT
1  ravi  37.0            3000         HR
2    ak  28.0           40000         IT
3    vj  19.0           50000         HR
4    av   NaN             555         IT

In [28]:
# Last 5 rows
df.tail()

   Name   Age  Monthly_Salary
1  ravi  37.0            3000
2    ak  28.0           40000
3    vj  19.0           50000
4    av   NaN             555
5    rj   3.0             777

In [29]:
# Random rows
df.sample(5)

  Name   Age  Monthly_Salary
0  ram  26.0           10000
2   ak  28.0           40000
4   av   NaN             555
3   vj  19.0           50000
5   rj   3.0             777

In [30]:
# Basic Information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            6 non-null      str
 1   Age             5 non-null      float64
 2   Monthly_Salary  6 non-null      int64
dtypes: float64(1), int64(1), str(1)
memory usage: 276.0 bytes

In [31]:
# Isse pata chalega:

# Total rows
# Columns
# Data types
# Missing values ka indication

In [32]:
# Statistical Summary
df.describe()

             Age  Monthly_Salary
count   5.000000        6.000000
mean   22.600000    17388.666667
std    12.700394    21889.346191
min     3.000000      555.000000
25%    19.000000     1332.750000
50%    26.000000     6500.000000
75%    28.000000    32500.000000
max    37.000000    50000.000000

In [33]:
# Ye numerical columns ka:

# Count
# Mean
# Standard deviation
# Minimum
# Maximum
# Quartiles

# dikhata hai.

In [34]:
# Columns
print(df.columns)

Index(['Name', 'Age', 'Monthly_Salary'], dtype='str')

In [35]:
#Specific column:
print(df["Monthly_Salary"])

0    10000
1     3000
2    40000
3    50000
4      555
5      777
Name: Monthly_Salary, dtype: int64

In [36]:
# Multiple Columns
print(df[["Name", "Monthly_Salary"]])

   Name  Monthly_Salary
0   ram           10000
1  ravi            3000
2    ak           40000
3    vj           50000
4    av             555
5    rj             777

In [37]:
# Rows Filter Karna
df[df["Monthly_Salary"] > 30000]  #Sirf un employees ko dikhao jinki salary ₹30,000 se zyada hai.

  Name   Age  Monthly_Salary
2   ak  28.0           40000
3   vj  19.0           50000

In [38]:
# Multiple Conditions
df[(df["Age"] > 22) & (df["Monthly_Salary"] > 30000)]

  Name   Age  Monthly_Salary
2   ak  28.0           40000

In [39]:
# Sorting
df.sort_values("Monthly_Salary")

   Name   Age  Monthly_Salary
4    av   NaN             555
5    rj   3.0             777
1  ravi  37.0            3000
0   ram  26.0           10000
2    ak  28.0           40000
3    vj  19.0           50000

In [40]:
# Descending
df.sort_values("Monthly_Salary", ascending=False)

   Name   Age  Monthly_Salary
3    vj  19.0           50000
2    ak  28.0           40000
0   ram  26.0           10000
1  ravi  37.0            3000
5    rj   3.0             777
4    av   NaN             555

In [41]:
# Missing Values

In [42]:
df.isnull().sum()

Name              0
Age               1
Monthly_Salary    0
dtype: int64

In [47]:
# Missing Values

In [48]:
df["Age"] = df["Age"].fillna(df["Age"].mean())
# df["Age"] = df["Age"].fillna(0)

In [49]:
df

   Name   Age  Monthly_Salary
0   ram  26.0           10000
1  ravi  37.0            3000
2    ak  28.0           40000
3    vj  19.0           50000
4    av  22.6             555
5    rj   3.0             777

In [50]:
# Duplicate Data

In [51]:
df.duplicated().sum()

np.int64(0)

In [52]:
# Duplicates remove:

In [53]:
df = df.drop_duplicates()