In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("sales.csv")
df

   Name   Age  Monthly_Salary Department
0   ram  26.0           10000         IT
1  ravi  37.0            3000         HR
2    ak  28.0           40000         IT
3    vj  19.0           50000         HR
4    av   NaN             555         IT
5    rj   3.0             777         HR

In [5]:
# Average salary department-wise:

In [6]:
df.groupby("Department")["Monthly_Salary"].mean()

Department
HR    17925.666667
IT    16851.666667
Name: Monthly_Salary, dtype: float64

In [7]:
# GroupBy + Sum

In [9]:
df.groupby("Department")["Monthly_Salary"].sum()

Department
HR    53777
IT    50555
Name: Monthly_Salary, dtype: int64

In [10]:
# Value Counts

In [11]:
df["Department"].value_counts()

Department
IT    3
HR    3
Name: count, dtype: int64

In [12]:
# New Column Suppose salary par 10% bonus:

In [14]:
df["Bonus"] = df["Monthly_Salary"] * 0.10

In [15]:
df

   Name   Age  Monthly_Salary Department   Bonus
0   ram  26.0           10000         IT  1000.0
1  ravi  37.0            3000         HR   300.0
2    ak  28.0           40000         IT  4000.0
3    vj  19.0           50000         HR  5000.0
4    av   NaN             555         IT    55.5
5    rj   3.0             777         HR    77.7

In [16]:
# Existing Columns se New Column

In [19]:
df["Total Salary"] = df["Monthly_Salary"] + df["Bonus"]
df

   Name   Age  Monthly_Salary Department   Bonus  Total Salary
0   ram  26.0           10000         IT  1000.0       11000.0
1  ravi  37.0            3000         HR   300.0        3300.0
2    ak  28.0           40000         IT  4000.0       44000.0
3    vj  19.0           50000         HR  5000.0       55000.0
4    av   NaN             555         IT    55.5         610.5
5    rj   3.0             777         HR    77.7         854.7