In [1]:
# # # Pandas — Data Analysis
# # 1. Pandas kya hai?

# # Pandas Python ki library hai jo tabular data ko read, clean, manipulate aur analyze karne ke
# liye use hoti hai
# | Name  | Age | Salary |
# | ----- | --: | -----: |
# | Rahul |  22 |  30000 |
# | Amit  |  24 |  40000 |
# | Neha  |  23 |  35000 |

In [2]:
!pip install Pandas

Requirement already satisfied: Pandas in C:\Users\jainv\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\jainv\AppData\Local\Programs\Python\Python314\Lib\site-packages (from Pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\jainv\AppData\Local\Programs\Python\Python314\Lib\site-packages (from Pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\jainv\AppData\Local\Programs\Python\Python314\Lib\site-packages (from Pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\jainv\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->Pandas) (1.17.0)

[notice] A new release of pip is available: 26.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
# Series ko simple way mein single column samajh sakte ho.
sales = pd.Series([12000, 15000, 18000, 22000])

print(sales)

0    12000
1    15000
2    18000
3    22000
dtype: int64

In [5]:
# DataFrame DataFrame = Rows + Columns

In [6]:
data = {
    "Name": ["Rahul", "Amit", "Neha"],
    "Age": [22, 24, 23],
    "Salary": [30000, 40000, 35000]
}

df = pd.DataFrame(data)

print(df) #DataFrame Excel table ki tarah hota hai.

    Name  Age  Salary
0  Rahul   22   30000
1   Amit   24   40000
2   Neha   23   35000

In [7]:
# CSV File Read Karna

In [8]:
df = pd.read_csv("sales.csv")

In [9]:
df

   Name   Age  Monthly_Salary Department
0   ram  26.0           10000         IT
1  ravi  37.0            3000         HR
2    ak  28.0           40000         IT
3    vj  19.0           50000         HR
4    av   NaN             555         IT
5    rj   3.0             777         HR

In [21]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 26.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:
# df = pd.read_excel("salespn.xlsx")
# !pip install openpyxl

In [10]:
df

   Name   Age  Monthly_Salary Department
0   ram  26.0           10000         IT
1  ravi  37.0            3000         HR
2    ak  28.0           40000         IT
3    vj  19.0           50000         HR
4    av   NaN             555         IT
5    rj   3.0             777         HR