In [1]:
import pandas as pd

In [2]:
data = {
    "Employee": ["Rahul", "Amit", "Neha", "Priya", "Rohit"],
    "Department": ["IT", "HR", "IT", "Sales", "IT"],
    "Salary": [40000, 30000, 50000, 35000, 45000],
    "Experience": [2, 1, 4, 2, 3]
}

df = pd.DataFrame(data)

print(df)

  Employee Department  Salary  Experience
0    Rahul         IT   40000           2
1     Amit         HR   30000           1
2     Neha         IT   50000           4
3    Priya      Sales   35000           2
4    Rohit         IT   45000           3

In [3]:
df["Salary"].mean() #Average salary

np.float64(40000.0)

In [5]:
df["Salary"].max()  #Highest salary?

np.int64(50000)

In [6]:
df[df["Department"] == "IT"]

  Employee Department  Salary  Experience
0    Rahul         IT   40000           2
2     Neha         IT   50000           4
4    Rohit         IT   45000           3

In [7]:
df.groupby("Department")["Salary"].mean()   #Department-wise average salary?

Department
HR       30000.0
IT       45000.0
Sales    35000.0
Name: Salary, dtype: float64

In [8]:
# 3+ years experience wale employees?
df[df["Experience"] >= 3]

  Employee Department  Salary  Experience
2     Neha         IT   50000           4
4    Rohit         IT   45000           3